---
# handlers file for roles/kubernetes-workers
- name: restart sysctl
  systemd:
    name: systemd-sysctl
    state: restarted
    daemon_reload: yes
  become: true

- name: restart docker
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
  become: true

- name: restart kubelet
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes
  become: true

- name: restart kube-proxy
  systemd:
    name: kube-proxy
    state: restarted
    daemon_reload: yes
  become: true

- name: restart kube-apiserver
  systemd:
    name: kube-apiserver
    state: restarted
    daemon_reload: yes
  become: true 

- name: restart kube-controller-manager
  systemd:
    name: kube-controller-manager
    state: restarted
    daemon_reload: yes
  become: true

- name: restart kube-scheduler
  systemd:
    name: kube-scheduler
    state: restarted
    daemon_reload: yes
  become: true

- name: restart containerd
  systemd:
    name: containerd
    state: restarted
    daemon_reload: yes
  become: true

- name: restart kubelet
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes
  become: true