---
infra:
  hosts:
    hosta:
      ansible_host: 172.16.28.13
    hostb:
      ansible_host: 172.16.28.42
    hostc:
      ansible_host: 172.16.28.41
  vars:
    ansible_user: centos
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
    ansible_ssh_pipelining: true
kube-workers:
  hosts:
    workera:
      ansible_host: 172.16.28.45
    workerb:
      ansible_host: 172.16.28.44
    workerc:
      ansible_host: 172.16.28.43
  vars:
    ansible_user: centos
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
    ansible_ssh_pipelining: true